<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class WPMailerDKIM {
	private $wp_mailer_dkim_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'wp_mailer_dkim_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'wp_mailer_dkim_page_init' ) );
	}

	public function wp_mailer_dkim_add_plugin_page() {
		add_options_page(
			'WP Mailer DKIM', // page_title
			'WP Mailer DKIM', // menu_title
			'manage_options', // capability
			'wp-mailer-dkim', // menu_slug
			array( $this, 'wp_mailer_dkim_create_admin_page' ) // function
		);
	}

	public function wp_mailer_dkim_create_admin_page() {
		$this->wp_mailer_dkim_options = get_option( 'wp_mailer_dkim_option_name' ); ?>

        <div class="wrap">
            <h2>WP Mailer DKIM</h2>
            <p></p>
			<?php settings_errors(); ?>

            <form method="post" action="options.php">
				<?php
				settings_fields( 'wp_mailer_dkim_option_group' );
				do_settings_sections( 'wp-mailer-dkim-admin' );
				submit_button();
				?>
            </form>
        </div>
	<?php }

	public function wp_mailer_dkim_page_init() {
		register_setting(
			'wp_mailer_dkim_option_group', // option_group
			'wp_mailer_dkim_option_name', // option_name
			array( $this, 'wp_mailer_dkim_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'wp_mailer_dkim_setting_section', // id
			'Settings', // title
			array( $this, 'wp_mailer_dkim_section_info' ), // callback
			'wp-mailer-dkim-admin' // page
		);

		add_settings_field(
			'domain_0', // id
			'Domain', // title
			array( $this, 'domain_0_callback' ), // callback
			'wp-mailer-dkim-admin', // page
			'wp_mailer_dkim_setting_section' // section
		);

		add_settings_field(
			'selector_1', // id
			'Selector', // title
			array( $this, 'selector_1_callback' ), // callback
			'wp-mailer-dkim-admin', // page
			'wp_mailer_dkim_setting_section' // section
		);

		add_settings_field(
			'private_key_2', // id
			'Private key', // title
			array( $this, 'private_key_2_callback' ), // callback
			'wp-mailer-dkim-admin', // page
			'wp_mailer_dkim_setting_section' // section
		);

		add_settings_field(
			'passphrase_3', // id
			'Passphrase', // title
			array( $this, 'passphrase_3_callback' ), // callback
			'wp-mailer-dkim-admin', // page
			'wp_mailer_dkim_setting_section' // section
		);
	}

	public function wp_mailer_dkim_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['domain_0'] ) ) {
			$sanitary_values['domain_0'] = sanitize_text_field( $input['domain_0'] );
		}

		if ( isset( $input['selector_1'] ) ) {
			$sanitary_values['selector_1'] = sanitize_text_field( $input['selector_1'] );
		}

		if ( isset( $input['private_key_2'] ) ) {
			$sanitary_values['private_key_2'] = esc_textarea( $input['private_key_2'] );
		}

		if ( isset( $input['passphrase_3'] ) ) {
			$sanitary_values['passphrase_3'] = sanitize_text_field( $input['passphrase_3'] );
		}

		return $sanitary_values;
	}

	public function wp_mailer_dkim_section_info() {

	}

	public function domain_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="wp_mailer_dkim_option_name[domain_0]" id="domain_0" value="%s">',
			isset( $this->wp_mailer_dkim_options['domain_0'] ) ? esc_attr( $this->wp_mailer_dkim_options['domain_0']) : ''
		);
	}

	public function selector_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="wp_mailer_dkim_option_name[selector_1]" id="selector_1" value="%s">',
			isset( $this->wp_mailer_dkim_options['selector_1'] ) ? esc_attr( $this->wp_mailer_dkim_options['selector_1']) : ''
		);
	}

	public function private_key_2_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="wp_mailer_dkim_option_name[private_key_2]" id="private_key_2">%s</textarea>',
			isset( $this->wp_mailer_dkim_options['private_key_2'] ) ? esc_attr( $this->wp_mailer_dkim_options['private_key_2']) : ''
		);
	}

	public function passphrase_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="wp_mailer_dkim_option_name[passphrase_3]" id="passphrase_3" value="%s">',
			isset( $this->wp_mailer_dkim_options['passphrase_3'] ) ? esc_attr( $this->wp_mailer_dkim_options['passphrase_3']) : ''
		);
	}

}
